name: Fix invalid require names

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  fix-require-names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run fix-invalid-require-names script
        run: node scripts/fix-invalid-require-names.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: fix invalid require variable names"
          git push
