# .github/workflows/bundle-to-cjs.yml
name: Bundle to CommonJS

on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install esbuild
        run: npm install esbuild --save-dev

      - name: Run bundler script
        run: node scripts/build-to-cjs.js

      - name: Commit bundled files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: bundle files to CJS using esbuild"
          git push
