name: Detect Circular Dependencies

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-circular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install madge
        run: npm install --save-dev madge

      - name: Detect circular dependencies
        run: |
          npx madge --circular src || (
            echo "\n❌ Circular dependencies detected!" && exit 1
          )
