name: Fix cleaners require paths

on:
  workflow_dispatch:

jobs:
  fix-cleaners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run fix-cleaners-require.js
        run: node scripts/fix-cleaners-require.js
