name: Fix Circular Requires

on:
  workflow_dispatch:

jobs:
  fix-circular-requires:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install madge
        run: npm install madge --legacy-peer-deps

      - name: Install glob
        run: npm install --save-dev glob --legacy-peer-deps

      - name: Run fix-circular-requires script
        run: node scripts/fix-circular-require.js

      - name: Commit & Push changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "🔁 Fix circular requires"
            git push
          else
            echo "✅ No changes to commit"
          fi
