name: Fix named exports (ESModules)

on:
  workflow_dispatch:

jobs:
  fix-named-exports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run named exports fix
        run: node scripts/fix-named-exports.js

      - name: Commit changes
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add .
          git commit -m "fix: convert named exports to CommonJS" || echo "No changes to commit"
          git push
