name: Convert ES Modules to CommonJS

on:
  workflow_dispatch:  # Αυτό σου επιτρέπει να το τρέχεις χειροκίνητα

jobs:
  convert-esm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run conversion script
        run: node scripts/convert-esm-to-cjs.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "fix: convert ESM to CommonJS"
          git push
